        <hr/>
        <!-- Footer -->
        <footer class="page-footer font-small teal pt-4">
        <div class="container-fluid text-center text-md-left">
        <div class="row">
        <div class="col-md-6 mt-md-0 mt-3">
        <h5 class="text-uppercase font-weight-bold">¿De qué trata?</h5>
        <p>Esta página trata de dos los lenguajes de programación muy importantes y de sus características.</p>
        </div>
        <hr class="clearfix w-100 d-md-none pb-3">
        <div class="col-md-6 mb-md-0 mb-3">
        <h5 class="text-uppercase font-weight-bold">¿Objetivo?</h5>
        <p>Practica para aprobar la asignatura de despliegue, ir a las prácticas y trabajar.</p>
        </div>
        </div>
        </div>
        <div class="footer-copyright text-center py-3">© 2019 Copyright:
        <a href="http://www.homerswebpage.com/" target="_blank">aportodas.com</a>
        </div>
        </footer>
        
    </div>
</body>
</html>